// <auto-generated />
using System;
using Instagram_Clone.ApplicationDBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Instagram_Clone.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240330180230_addingExercises")]
    partial class addingExercises
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Instagram_Clone.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseReps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestBetweenExercises")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseName = "Push-up",
                            ExerciseReps = "15 reps",
                            ExerciseTime = "30 seconds",
                            RestBetweenExercises = "10 seconds"
                        },
                        new
                        {
                            Id = 2,
                            ExerciseName = "Squats",
                            ExerciseReps = "20 reps",
                            ExerciseTime = "45 seconds",
                            RestBetweenExercises = "15 seconds"
                        },
                        new
                        {
                            Id = 3,
                            ExerciseName = "Plank",
                            ExerciseReps = "N/A",
                            ExerciseTime = "1 minute",
                            RestBetweenExercises = "10 seconds"
                        },
                        new
                        {
                            Id = 4,
                            ExerciseName = "Lunges",
                            ExerciseReps = "12 reps per leg",
                            ExerciseTime = "45 seconds",
                            RestBetweenExercises = "10 seconds"
                        },
                        new
                        {
                            Id = 5,
                            ExerciseName = "Burpees",
                            ExerciseReps = "12 reps",
                            ExerciseTime = "45 seconds",
                            RestBetweenExercises = "15 seconds"
                        },
                        new
                        {
                            Id = 6,
                            ExerciseName = "Mountain Climbers",
                            ExerciseReps = "20 reps",
                            ExerciseTime = "45 seconds",
                            RestBetweenExercises = "10 seconds"
                        },
                        new
                        {
                            Id = 7,
                            ExerciseName = "Sit-ups",
                            ExerciseReps = "20 reps",
                            ExerciseTime = "1 minute",
                            RestBetweenExercises = "10 seconds"
                        },
                        new
                        {
                            Id = 8,
                            ExerciseName = "Jumping Jacks",
                            ExerciseReps = "30 reps",
                            ExerciseTime = "1 minute",
                            RestBetweenExercises = "10 seconds"
                        },
                        new
                        {
                            Id = 9,
                            ExerciseName = "High Knees",
                            ExerciseReps = "30 reps",
                            ExerciseTime = "45 seconds",
                            RestBetweenExercises = "10 seconds"
                        },
                        new
                        {
                            Id = 10,
                            ExerciseName = "Plank Jacks",
                            ExerciseReps = "20 reps",
                            ExerciseTime = "30 seconds",
                            RestBetweenExercises = "10 seconds"
                        },
                        new
                        {
                            Id = 11,
                            ExerciseName = "Russian Twists",
                            ExerciseReps = "20 reps",
                            ExerciseTime = "1 minute",
                            RestBetweenExercises = "10 seconds"
                        },
                        new
                        {
                            Id = 12,
                            ExerciseName = "Wall Sit",
                            ExerciseReps = "N/A",
                            ExerciseTime = "1 minute",
                            RestBetweenExercises = "10 seconds"
                        },
                        new
                        {
                            Id = 13,
                            ExerciseName = "Tricep Dips",
                            ExerciseReps = "15 reps",
                            ExerciseTime = "45 seconds",
                            RestBetweenExercises = "10 seconds"
                        },
                        new
                        {
                            Id = 14,
                            ExerciseName = "Bicycle Crunches",
                            ExerciseReps = "20 reps",
                            ExerciseTime = "1 minute",
                            RestBetweenExercises = "10 seconds"
                        },
                        new
                        {
                            Id = 15,
                            ExerciseName = "Calf Raises",
                            ExerciseReps = "20 reps",
                            ExerciseTime = "45 seconds",
                            RestBetweenExercises = "10 seconds"
                        },
                        new
                        {
                            Id = 16,
                            ExerciseName = "Shoulder Press",
                            ExerciseReps = "12 reps",
                            ExerciseTime = "45 seconds",
                            RestBetweenExercises = "10 seconds"
                        },
                        new
                        {
                            Id = 17,
                            ExerciseName = "Dead Bug",
                            ExerciseReps = "20 reps",
                            ExerciseTime = "1 minute",
                            RestBetweenExercises = "10 seconds"
                        },
                        new
                        {
                            Id = 18,
                            ExerciseName = "Superman",
                            ExerciseReps = "10",
                            ExerciseTime = "1 minute",
                            RestBetweenExercises = "10 seconds"
                        },
                        new
                        {
                            Id = 19,
                            ExerciseName = "Reverse Crunches",
                            ExerciseReps = "15 reps",
                            ExerciseTime = "45 seconds",
                            RestBetweenExercises = "10 seconds"
                        },
                        new
                        {
                            Id = 20,
                            ExerciseName = "Jump Rope",
                            ExerciseReps = "N/A",
                            ExerciseTime = "1 minute",
                            RestBetweenExercises = "10 seconds"
                        });
                });

            modelBuilder.Entity("Instagram_Clone.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Instagram_Clone.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Instagram_Clone.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Instagram_Clone.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Instagram_Clone.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
